version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - slack/notify:
          event: always
          mentions: '@channel'
          template: success_tagged_deploy_1
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run
      - slack/notify:
          event: fail
          mentions: '@channel'
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: '@channel'
          template: basic_success_1
workflows:
  deploy_and_notify:
    jobs:
      - build:
          context: slack-secrets